### ISSUE TITLE
Visualization Code for Trinity Dataset

### ISSUE THREAD

**Issue by JeremyCJM** [yesheng-THU/GFGE#5]
Hi Yesheng,

Could you also release the code for visualizing the results of the Trinity dataset? What is the next step after running the sampling of Trinity?

Thanks,
Jeremy

**Comment by yec22** [comment]
For visualizing the results of the Trinity dataset, we manually retarget the motion sequences(.bvh files) to several 3D characters using Blender. Therefore, we don't have the code for visualizing.

**Comment by yesheng-THU** [comment]
For visualizing the results of the Trinity dataset, we manually retarget the motion sequences(.bvh files) to several 3D characters using Blender. Therefore, we don't provide the code for visualizing.
