### ISSUE TITLE
Beat Alignment Score

### ISSUE THREAD

**Issue by JeremyCJM** [yesheng-THU/GFGE#6]
Hi Yesheng,

Did you implement the **Beat Alignment** (BA) score in this repo? I did not find it. Could you tell me where is the code for BA score?

Thanks,
Jeremy

**Comment by yesheng-THU** [comment]
We didn't release the Beat Alignment (BA) score in this repo. You can refer to https://github.com/google-research/mint for implementation details. (https://github.com/alvinliu0/HA2G may also help.)
